//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoTool.Model.DBTransfer {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBTransferResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBTransferResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProntoTool.Model.DBTransfer.DBTransferResources", typeof(DBTransferResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client ähnelt.
        /// </summary>
        internal static string ClientKeyDBTransfer {
            get {
                return ResourceManager.GetString("ClientKeyDBTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direct ähnelt.
        /// </summary>
        internal static string ClientTypePronto {
            get {
                return ResourceManager.GetString("ClientTypePronto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        internal static string DatabaseKeyDBTransfer {
            get {
                return ResourceManager.GetString("DatabaseKeyDBTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DATABASE NAME ähnelt.
        /// </summary>
        internal static string DatabaseNameKeyPronto {
            get {
                return ResourceManager.GetString("DatabaseNameKeyPronto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        internal static string DatabaseSectionKeyPronto {
            get {
                return ResourceManager.GetString("DatabaseSectionKeyPronto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ini ähnelt.
        /// </summary>
        internal static string IniFileExtension {
            get {
                return ResourceManager.GetString("IniFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Instance ähnelt.
        /// </summary>
        internal static string InstanceKeyDBTransfer {
            get {
                return ResourceManager.GetString("InstanceKeyDBTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRONTO ähnelt.
        /// </summary>
        internal static string InstanceNamePronto {
            get {
                return ResourceManager.GetString("InstanceNamePronto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modus ähnelt.
        /// </summary>
        internal static string ModeKeyDBTransfer {
            get {
                return ResourceManager.GetString("ModeKeyDBTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 ähnelt.
        /// </summary>
        internal static string ModePronto {
            get {
                return ResourceManager.GetString("ModePronto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string PasswordKeyDBTransfer {
            get {
                return ResourceManager.GetString("PasswordKeyDBTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die oasoas ähnelt.
        /// </summary>
        internal static string PasswordPronto {
            get {
                return ResourceManager.GetString("PasswordPronto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provider ähnelt.
        /// </summary>
        internal static string ProviderKeyDBTransfer {
            get {
                return ResourceManager.GetString("ProviderKeyDBTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQL Server ähnelt.
        /// </summary>
        internal static string RadiobuttonOracle {
            get {
                return ResourceManager.GetString("RadiobuttonOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oracle ähnelt.
        /// </summary>
        internal static string RadiobuttonSqlServer {
            get {
                return ResourceManager.GetString("RadiobuttonSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server ähnelt.
        /// </summary>
        internal static string ServerNameKeyDBTransfer {
            get {
                return ResourceManager.GetString("ServerNameKeyDBTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SERVER NAME ähnelt.
        /// </summary>
        internal static string ServerNameKeyPronto {
            get {
                return ResourceManager.GetString("ServerNameKeyPronto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl der Quellkonfiguration ähnelt.
        /// </summary>
        internal static string SourceConfigDialogTitle {
            get {
                return ResourceManager.GetString("SourceConfigDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl der Zielkonfiguration ähnelt.
        /// </summary>
        internal static string TargetConfigDialogTitle {
            get {
                return ResourceManager.GetString("TargetConfigDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        internal static string UserNameKeyDBTransfer {
            get {
                return ResourceManager.GetString("UserNameKeyDBTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die USER NAME ähnelt.
        /// </summary>
        internal static string UserNameKeyPronto {
            get {
                return ResourceManager.GetString("UserNameKeyPronto", resourceCulture);
            }
        }
    }
}
