@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "project.docmaker.model.Section",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_853980684 { 
   	label=docmaker
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1812194503 { 
   	label=model
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ClassSection1793065924[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ClassSection</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   fields: List&lt;FieldSection&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   methods: List&lt;MethodSection&gt; [0..*]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Description1793065924[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Description</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   descriptionText: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sectionClass: Class&lt;? extends Section&gt; [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FieldSection1793065924[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FieldSection</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Header1793065924[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Header</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   content: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sectionClass: Class&lt;? extends Section&gt; [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MethodSection1793065924[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MethodSection</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ParamTag802806040[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ParamTag</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   tagContent: ParamTagContent [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ParamTagContent837532723[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ParamTagContent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   paramName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   paramValue: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ paramName(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ paramValue(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ReturnTag802806040[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReturnTag</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   tagContent: ReturnTagContent [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ReturnTagContent1608045732[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReturnTagContent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   content: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ content(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Section1793065924[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Section</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   description: Description [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   header: Header [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tags: DocumentationTag&lt;?&gt;[] [0..*]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ClassSection1793065924 -> FieldSection1793065924[label="fields
[0..*]"];
ClassSection1793065924 -> MethodSection1793065924[label="methods
[0..*]"];
ParamTag802806040 -> ParamTagContent837532723[label="tagContent
[0..1]"];
ReturnTag802806040 -> ReturnTagContent1608045732[label="tagContent
[0..1]"];
ReturnTagContent1608045732 -> ParamTagContent837532723[arrowhead=none];
Section1793065924 -> ClassSection1793065924[arrowhead=none, arrowtail=empty, dir=both];
Section1793065924 -> Description1793065924[label="description
[0..1]"];
Section1793065924 -> FieldSection1793065924[arrowhead=none, arrowtail=empty, dir=both];
Section1793065924 -> Header1793065924[label="header
[0..1]"];
Section1793065924 -> MethodSection1793065924[arrowhead=none, arrowtail=empty, dir=both];
Section1793065924 -> ParamTag802806040[arrowhead=none];
Section1793065924 -> ReturnTag802806040[arrowhead=none];
    
}
@enduml