//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProntoTool.Model.Translator {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProntoTool.Model.Translator.TranslationResources", typeof(TranslationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die d2462b2c-74e2-4e7a-98df-d0172f9c4f2b:fx ähnelt.
        /// </summary>
        internal static string AUTHENTIFICATION_KEY {
            get {
                return ResourceManager.GetString("AUTHENTIFICATION_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \%[0 #+-]?[0-9*]*\.?\*?\d*[hl]{0,2}[jztL]?[diuoxXeEfgGaAcpsSn%] ähnelt.
        /// </summary>
        internal static string FORMAT_REGEX_PATTERN {
            get {
                return ResourceManager.GetString("FORMAT_REGEX_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde keine Glossar-Datenbank in den Startparametern angegeben! ähnelt.
        /// </summary>
        internal static string GLOSSARY_ARGUMENT_EXCEPTION_MSG {
            get {
                return ResourceManager.GetString("GLOSSARY_ARGUMENT_EXCEPTION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT GERMAN,{0},{1} FROM {2} ähnelt.
        /// </summary>
        internal static string GLOSSARY_CONTAINER_SQL_PATTERN {
            get {
                return ResourceManager.GetString("GLOSSARY_CONTAINER_SQL_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; mit {1} Einträgen erstellt. ähnelt.
        /// </summary>
        internal static string GLOSSARY_CREATED_MSG {
            get {
                return ResourceManager.GetString("GLOSSARY_CREATED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glossar Pronto {0}-{1} ähnelt.
        /// </summary>
        internal static string GLOSSARY_NAME {
            get {
                return ResourceManager.GetString("GLOSSARY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LANGTRANS ähnelt.
        /// </summary>
        internal static string GLOSSARY_TABLE {
            get {
                return ResourceManager.GetString("GLOSSARY_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT GERMAN,{0},{1} FROM {2} WHERE {1} IS NULL OR {1} IS &apos;&apos; ähnelt.
        /// </summary>
        internal static string TRANSLATION_CONTAINER_SQL_PATTERN {
            get {
                return ResourceManager.GetString("TRANSLATION_CONTAINER_SQL_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersetzungsprozess wurde abgeschlossen. Siehe Logging für weitere Informationen. ähnelt.
        /// </summary>
        internal static string TRANSLATION_FINISHED {
            get {
                return ResourceManager.GetString("TRANSLATION_FINISHED", resourceCulture);
            }
        }
    }
}
